target 'LeanplumSegment_Example' do
  use_frameworks!
    pod 'LeanplumSegment', :path => '../'
  target 'LeanplumSegment_Tests' do
    pod 'LeanplumSegment', :path => '../'
    pod 'OCMock', '~> 3.2.2'
  end
end
